/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.recurso.master.logic.dto;

import co.edu.uniandes.csw.SOFPA.comentario.logic.dto.ComentarioDTO;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _RecursoMasterDTO {

 
    protected RecursoDTO recursoEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public RecursoDTO getRecursoEntity() {
        return recursoEntity;
    }

    public void setRecursoEntity(RecursoDTO recursoEntity) {
        this.recursoEntity = recursoEntity;
    }
    
    public List<ComentarioDTO> createpublicacion;
    public List<ComentarioDTO> updatepublicacion;
    public List<ComentarioDTO> deletepublicacion;
    public List<ComentarioDTO> listpublicacion;	
    public List<UsuarioDTO> createestudiantes_recientes;
    public List<UsuarioDTO> updateestudiantes_recientes;
    public List<UsuarioDTO> deleteestudiantes_recientes;
    public List<UsuarioDTO> listestudiantes_recientes;	
	
	
	
    public List<ComentarioDTO> getCreatepublicacion(){ return createpublicacion; };
    public void setCreatepublicacion(List<ComentarioDTO> createpublicacion){ this.createpublicacion=createpublicacion; };
    public List<ComentarioDTO> getUpdatepublicacion(){ return updatepublicacion; };
    public void setUpdatepublicacion(List<ComentarioDTO> updatepublicacion){ this.updatepublicacion=updatepublicacion; };
    public List<ComentarioDTO> getDeletepublicacion(){ return deletepublicacion; };
    public void setDeletepublicacion(List<ComentarioDTO> deletepublicacion){ this.deletepublicacion=deletepublicacion; };
    public List<ComentarioDTO> getListpublicacion(){ return listpublicacion; };
    public void setListpublicacion(List<ComentarioDTO> listpublicacion){ this.listpublicacion=listpublicacion; };	
    public List<UsuarioDTO> getCreateestudiantes_recientes(){ return createestudiantes_recientes; };
    public void setCreateestudiantes_recientes(List<UsuarioDTO> createestudiantes_recientes){ this.createestudiantes_recientes=createestudiantes_recientes; };
    public List<UsuarioDTO> getUpdateestudiantes_recientes(){ return updateestudiantes_recientes; };
    public void setUpdateestudiantes_recientes(List<UsuarioDTO> updateestudiantes_recientes){ this.updateestudiantes_recientes=updateestudiantes_recientes; };
    public List<UsuarioDTO> getDeleteestudiantes_recientes(){ return deleteestudiantes_recientes; };
    public void setDeleteestudiantes_recientes(List<UsuarioDTO> deleteestudiantes_recientes){ this.deleteestudiantes_recientes=deleteestudiantes_recientes; };
    public List<UsuarioDTO> getListestudiantes_recientes(){ return listestudiantes_recientes; };
    public void setListestudiantes_recientes(List<UsuarioDTO> listestudiantes_recientes){ this.listestudiantes_recientes=listestudiantes_recientes; };	
	
	
}

