/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.recurso.persistence.entity;

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class _RecursoEntity {

	private String tema;
	private String tipo;
	private String curso;
	private Integer dificultad;
	private String semestre;
	private Boolean avalado;
	private Integer cantidadVisitas;
	@Temporal(TemporalType.DATE)
	private Date ultimaFechaVisita;
	@Id
	@GeneratedValue(generator = "Recurso")
	private Long id;
	private String name;
	private String uRL;

	public String getTema(){
		return tema;
	}
	
	public void setTema(String tema){
		this.tema = tema;
	}
	public String getTipo(){
		return tipo;
	}
	
	public void setTipo(String tipo){
		this.tipo = tipo;
	}
	public String getCurso(){
		return curso;
	}
	
	public void setCurso(String curso){
		this.curso = curso;
	}
	public Integer getDificultad(){
		return dificultad;
	}
	
	public void setDificultad(Integer dificultad){
		this.dificultad = dificultad;
	}
	public String getSemestre(){
		return semestre;
	}
	
	public void setSemestre(String semestre){
		this.semestre = semestre;
	}
	public Boolean getAvalado(){
		return avalado;
	}
	
	public void setAvalado(Boolean avalado){
		this.avalado = avalado;
	}
	public Integer getCantidadVisitas(){
		return cantidadVisitas;
	}
	
	public void setCantidadVisitas(Integer cantidadVisitas){
		this.cantidadVisitas = cantidadVisitas;
	}
	public Date getUltimaFechaVisita(){
		return ultimaFechaVisita;
	}
	
	public void setUltimaFechaVisita(Date ultimaFechaVisita){
		this.ultimaFechaVisita = ultimaFechaVisita;
	}
	public Long getId(){
		return id;
	}
	
	public void setId(Long id){
		this.id = id;
	}
	public String getName(){
		return name;
	}
	
	public void setName(String name){
		this.name = name;
	}
	public String getURL(){
		return uRL;
	}
	
	public void setURL(String uRL){
		this.uRL = uRL;
	}
}