/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.recurso.service;

import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoPageDTO;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.converter.RecursoConverter;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.entity.RecursoEntity;
import java.util.List;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.File;

import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

import org.glassfish.jersey.media.multipart.FormDataContentDisposition;
import org.glassfish.jersey.media.multipart.FormDataParam;

@Path("/Recurso")
@Stateless
public class RecursoService extends _RecursoService {
    
    @Context
    UriInfo uriInfo;
    
    @GET
    @Override
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public RecursoPageDTO getRecursos(@QueryParam("page") Integer page, @QueryParam("maxRecords")Integer maxRecords){
        
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        String tema = queryParams.getFirst("tema");
        if( tema != null && !tema.isEmpty()){
            return recursoLogicService.getRecursosPorTema(tema);
        }
        return super.getRecursos(page, maxRecords);
    }
    
    @POST
    @Path("/upload")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public RecursoDTO uploadArchive(@QueryParam("file") File file){
        try{
                String fileName = file.getName();
                String filePath = "C:/Users/estudiante/Documents/datos/"+fileName;
                OutputStream fileOS = new FileOutputStream(filePath);
            }catch(Exception e){
                    
            }
        return null;
    }
    
    
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public String cargarArchivo(@FormDataParam("file")InputStream fileIS, @FormDataParam("file")FormDataContentDisposition content)throws FileNotFoundException, IOException{
       String fileName = content.getFileName();
       String filePath = "C:/Users/estudiante/Documents/datos/" + fileName;
       try{
           OutputStream fileOS = new FileOutputStream(filePath);
	   System.out.println("***** fileName " + content.getFileName());
           int read = 0;
           final byte[] bytes = new byte[1024];
           while((read = fileIS.read(bytes))!=-1){
               fileOS.write(bytes, 0, read);
           }
       }catch(FileNotFoundException e){
           return "El archivo no existe o la ruta esta mal escrita.";
       }catch(IOException e){
           return " =( Error critico al subir un archivo, por favor comuniquese con el desarrollador.";
       }
       return "Archivo subido correctamente";
    }
}