/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.recurso.master.logic.ejb;

import co.edu.uniandes.csw.SOFPA.comentario.logic.dto.ComentarioDTO;
import co.edu.uniandes.csw.SOFPA.comentario.persistence.api.IComentarioPersistence;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.SOFPA.usuario.persistence.api.IUsuarioPersistence;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.SOFPA.recurso.master.logic.api._IRecursoMasterLogicService;
import co.edu.uniandes.csw.SOFPA.recurso.master.logic.dto.RecursoMasterDTO;
import co.edu.uniandes.csw.SOFPA.recurso.master.persistence.api.IRecursoMasterPersistence;
import co.edu.uniandes.csw.SOFPA.recurso.master.persistence.entity.RecursopublicacionEntity;
import co.edu.uniandes.csw.SOFPA.recurso.master.persistence.entity.Recursoestudiantes_recientesEntity;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.api.IRecursoPersistence;
import javax.inject.Inject;

public abstract class _RecursoMasterLogicService implements _IRecursoMasterLogicService {

    @Inject
    protected IRecursoPersistence recursoPersistance;
    @Inject
    protected IRecursoMasterPersistence recursoMasterPersistance;
    @Inject
    protected IComentarioPersistence comentarioPersistance;
    @Inject
    protected IUsuarioPersistence usuarioPersistance;

    public RecursoMasterDTO createMasterRecurso(RecursoMasterDTO recurso) {
        RecursoDTO persistedRecursoDTO = recursoPersistance.createRecurso(recurso.getRecursoEntity());
        if (recurso.getCreatepublicacion() != null) {
            for (ComentarioDTO comentarioDTO : recurso.getCreatepublicacion()) {
                ComentarioDTO createdComentarioDTO = comentarioPersistance.createComentario(comentarioDTO);
                RecursopublicacionEntity recursoComentarioEntity = new RecursopublicacionEntity(persistedRecursoDTO.getId(), createdComentarioDTO.getId());
                recursoMasterPersistance.createRecursopublicacionEntity(recursoComentarioEntity);
            }
        }
        if (recurso.getCreateestudiantes_recientes() != null) {
            for (UsuarioDTO usuarioDTO : recurso.getCreateestudiantes_recientes()) {
                UsuarioDTO createdUsuarioDTO = usuarioPersistance.createUsuario(usuarioDTO);
                Recursoestudiantes_recientesEntity recursoUsuarioEntity = new Recursoestudiantes_recientesEntity(persistedRecursoDTO.getId(), createdUsuarioDTO.getId());
                recursoMasterPersistance.createRecursoestudiantes_recientesEntity(recursoUsuarioEntity);
            }
        }
        // update comentario
        if (recurso.getUpdatepublicacion() != null) {
            for (ComentarioDTO comentarioDTO : recurso.getUpdatepublicacion()) {
                comentarioPersistance.updateComentario(comentarioDTO);
                RecursopublicacionEntity recursoComentarioEntity = new RecursopublicacionEntity(persistedRecursoDTO.getId(), comentarioDTO.getId());
                recursoMasterPersistance.createRecursopublicacionEntity(recursoComentarioEntity);
            }
        }
        // update usuario
        if (recurso.getUpdateestudiantes_recientes() != null) {
            for (UsuarioDTO usuarioDTO : recurso.getUpdateestudiantes_recientes()) {
                usuarioPersistance.updateUsuario(usuarioDTO);
                Recursoestudiantes_recientesEntity recursoUsuarioEntity = new Recursoestudiantes_recientesEntity(persistedRecursoDTO.getId(), usuarioDTO.getId());
                recursoMasterPersistance.createRecursoestudiantes_recientesEntity(recursoUsuarioEntity);
            }
        }
        return recurso;
    }

    public RecursoMasterDTO getMasterRecurso(Long id) {
        return recursoMasterPersistance.getRecurso(id);
    }

    public void deleteMasterRecurso(Long id) {
        recursoPersistance.deleteRecurso(id);
    }

    public void updateMasterRecurso(RecursoMasterDTO recurso) {
        recursoPersistance.updateRecurso(recurso.getRecursoEntity());

        //---- FOR RELATIONSHIP
        // persist new comentario
        if (recurso.getCreatepublicacion() != null) {
            for (ComentarioDTO comentarioDTO : recurso.getCreatepublicacion()) {
                ComentarioDTO createdComentarioDTO = comentarioPersistance.createComentario(comentarioDTO);
                RecursopublicacionEntity recursoComentarioEntity = new RecursopublicacionEntity(recurso.getRecursoEntity().getId(), createdComentarioDTO.getId());
                recursoMasterPersistance.createRecursopublicacionEntity(recursoComentarioEntity);
            }
        }
        // update comentario
        if (recurso.getUpdatepublicacion() != null) {
            for (ComentarioDTO comentarioDTO : recurso.getUpdatepublicacion()) {
                comentarioPersistance.updateComentario(comentarioDTO);
            }
        }
        // delete comentario
        if (recurso.getDeletepublicacion() != null) {
            for (ComentarioDTO comentarioDTO : recurso.getDeletepublicacion()) {
                recursoMasterPersistance.deleteRecursopublicacionEntity(recurso.getRecursoEntity().getId(), comentarioDTO.getId());
                comentarioPersistance.deleteComentario(comentarioDTO.getId());
            }
        }
        // delete usuario
        if (recurso.getDeleteestudiantes_recientes() != null) {
            for (UsuarioDTO usuarioDTO : recurso.getDeleteestudiantes_recientes()) {
                recursoMasterPersistance.deleteRecursoestudiantes_recientesEntity(recurso.getRecursoEntity().getId(), usuarioDTO.getId());
            }
        }
        // persist new usuario
        if (recurso.getCreateestudiantes_recientes() != null) {
            for (UsuarioDTO usuarioDTO : recurso.getCreateestudiantes_recientes()) {
                Recursoestudiantes_recientesEntity recursoUsuarioEntity = new Recursoestudiantes_recientesEntity(recurso.getRecursoEntity().getId(), usuarioDTO.getId());
                recursoMasterPersistance.createRecursoestudiantes_recientesEntity(recursoUsuarioEntity);
            }
        }
        // update usuario
        if (recurso.getUpdateestudiantes_recientes() != null) {
            for (UsuarioDTO usuarioDTO : recurso.getUpdateestudiantes_recientes()) {
                recursoMasterPersistance.deleteRecursoestudiantes_recientesEntity(recurso.getRecursoEntity().getId(), usuarioDTO.getId());
                usuarioPersistance.updateUsuario(usuarioDTO);
                Recursoestudiantes_recientesEntity recursoUsuarioEntity = new Recursoestudiantes_recientesEntity(recurso.getId(), usuarioDTO.getId());
                recursoMasterPersistance.createRecursoestudiantes_recientesEntity(recursoUsuarioEntity);
                
            }
        }
    }
}
