/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.usuario.persistence.entity;

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class _UsuarioEntity {

	private Integer cantidadVisitas;
	private String carrera;
	private String cursoActual;
	private String codigo;
	private String seccMagistral;
	private String seccComplementaria;
	@Id
	@GeneratedValue(generator = "Usuario")
	private Long id;
	private String name;
	private String apellidos;
	private String contrasenia;
	private String correo;
	private String rol;

	public Integer getCantidadVisitas(){
		return cantidadVisitas;
	}
	
	public void setCantidadVisitas(Integer cantidadVisitas){
		this.cantidadVisitas = cantidadVisitas;
	}
	public String getCarrera(){
		return carrera;
	}
	
	public void setCarrera(String carrera){
		this.carrera = carrera;
	}
	public String getCursoActual(){
		return cursoActual;
	}
	
	public void setCursoActual(String cursoActual){
		this.cursoActual = cursoActual;
	}
	public String getCodigo(){
		return codigo;
	}
	
	public void setCodigo(String codigo){
		this.codigo = codigo;
	}
	public String getSeccMagistral(){
		return seccMagistral;
	}
	
	public void setSeccMagistral(String seccMagistral){
		this.seccMagistral = seccMagistral;
	}
	public String getSeccComplementaria(){
		return seccComplementaria;
	}
	
	public void setSeccComplementaria(String seccComplementaria){
		this.seccComplementaria = seccComplementaria;
	}
	public Long getId(){
		return id;
	}
	
	public void setId(Long id){
		this.id = id;
	}
	public String getName(){
		return name;
	}
	
	public void setName(String name){
		this.name = name;
	}
	public String getApellidos(){
		return apellidos;
	}
	
	public void setApellidos(String apellidos){
		this.apellidos = apellidos;
	}
	public String getContrasenia(){
		return contrasenia;
	}
	
	public void setContrasenia(String contrasenia){
		this.contrasenia = contrasenia;
	}
	public String getCorreo(){
		return correo;
	}
	
	public void setCorreo(String correo){
		this.correo = correo;
	}
	public String getRol(){
		return rol;
	}
	
	public void setRol(String rol){
		this.rol = rol;
	}
}